# Generated by Django 5.2.7 on 2025-11-09 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('abrev', models.CharField(editable=False, max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('abrev', models.CharField(editable=False, max_length=3)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subareas', to='planos.area')),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('codigo', models.CharField(editable=False, max_length=40, unique=True)),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos', to='planos.subarea')),
            ],
        ),
        migrations.AddConstraint(
            model_name='subarea',
            constraint=models.UniqueConstraint(fields=('area', 'nombre'), name='uniq_subarea_por_area'),
        ),
        migrations.AddConstraint(
            model_name='plano',
            constraint=models.UniqueConstraint(fields=('subarea', 'titulo', 'version'), name='uniq_plano_por_subarea_y_version'),
        ),
    ]
